# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e26b0f7a35717af3ed66b624b2d605e4f95aa72c79cc522478450a9f6f8ab2f773e15dc97868b7fb1e829a6695938d25db17c0df9c87f172a911a833fe0ab65

test:
  secret_key_base: 18892f5df345842d50b8f5881a6e4f21581e41e26128b9edf8d978468cdad0454f28ff6f22e810d3a6552a304f90426413a8bad84b5d1ec7a75d022f1a323ef4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
